name: Build and Test on macOS

on:
  push:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'lolly/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-macos.yml'
      - 'xmake.lua' 
  pull_request:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'lolly/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-macos.yml'
      - 'xmake.lua' 

jobs:
  macosbuild:
    runs-on: macos-11
    strategy:
      matrix:
        malloc:
          [mimalloc, default]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            /Users/runner/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}

      - name: set XMAKE_GLOBALDIR
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
          actions-cache-folder: '.xmake-cache'

      - name: xmake repo --update
        run: xmake repo --update

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ runner.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-qt${{ matrix.qt_ver }}-${{ hashFiles('**/xmake.lua') }}

      - name: config
        run: xmake config --policies=build.ccache -o ${{ runner.workspace }}/build --yes -vD  --malloc=${{ matrix.malloc }} --enable_tests=true
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: |
          xmake run --yes -vD --group=tests
          xmake test -vD
      - name: benchmark
        run: xmake run --yes --group=bench
