name: Build on windows

on:
  push:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-windows.yml'
      - 'xmake.lua' 
  pull_request:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-windows.yml'
      - 'xmake.lua' 
  workflow_dispatch:

jobs:
  windowsbuild:
    runs-on: windows-2019
    env:
        # Force xmake to a specific folder (for cache)
        XMAKE_GLOBALDIR: ${{ github.workspace }}/.xmake-global
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.2
      - name: update repo
        run: xmake repo -u
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - name: config
        run: xmake config --yes -vD
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: xmake run --yes -vD --group=tests
