name: Build on wasm

on:
  push:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'lolly/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-wasm.yml'
      - 'xmake.lua' 
  pull_request:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'lolly/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-wasm.yml'
      - 'xmake.lua' 
  workflow_dispatch:

jobs:
  linuxbuild:
    runs-on: ubuntu-22.04
    steps:
      - uses: elves/setup-elvish@v1
        with:
          elvish-version: 0.19.2
      - name: Set xmake global dir
        run: |
          echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/.xmake-global" >> "${{ github.env }}"
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
      - name: update repo
        run: |
          xmake repo -u
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/xmake.lua') }}
      - name: config
        run: xmake config --yes -p wasm -vD
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: elvish bin/test_wasm
  windowsbuild:
    runs-on: windows-2019
    env:
      # Force xmake to a specific folder (for cache)
      XMAKE_GLOBALDIR: "${{ github.workspace }}\\.xmake-global"
    steps:
      - uses: elves/setup-elvish@v1
        with:
          elvish-version: 0.19.2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
      - name: update repo
        run: |
          xrepo update-repo
      - name: git crlf
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache packages from xrepo
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/xmake.lua') }}
      - name: config
        run: xmake config --yes -p wasm -vD --enable_tests=true
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: elvish bin/test_wasm

