name: Build on Debian bookworm
on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "!src/Plugins/Macos/**"
      - "!src/Plugins/Windows/**"
      - "tests/**"
      - "xmake.lua"
      - "xmake/packages.lua"
      - "xmake/packages/**"
      - ".github/workflows/ci-debia12.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "!src/Plugins/Macos/**"
      - "!src/Plugins/Windows/**"
      - "tests/**"
      - "xmake.lua"
      - "xmake/packages.lua"
      - "xmake/packages/**"
      - ".github/workflows/ci-debian12.yml"

env:
  XMAKE_ROOT: y
  QT_QPA_PLATFORM: offscreen
  INSTALL_DIR: tmp/build/packages/app.mogan/

jobs:
  build:
    container: debian:13
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y gcc git 7zip unzip curl build-essential \
              fonts-noto-cjk libcurl4-openssl-dev libfreetype-dev libfontconfig-dev \
              libmimalloc-dev libgit2-dev zlib1g-dev libssl-dev libjpeg62-turbo-dev cmake \
              qt6-base-dev libqt6svg6-dev qt6-image-formats-plugins pandoc
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: git add safe directory
        run: git config --global --add safe.directory '*'

      - name: set XMAKE_GLOBALDIR
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
          actions-cache-folder: ".xmake-cache"

      - name: xmake repo --update
        run: xmake repo --update

      - name: cache packages from xrepo
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-qt6-${{ hashFiles('**/packages.lua') }}

      - name: cache xmake
        uses: actions/cache@v3
        with:
          path: |
            tmp/build/.build_cache
          key: ${{ runner.os }}-build-qt6-${{ hashFiles('**/packages.lua') }}

      - name: config
        run: xmake config -vD --policies=build.ccache -o tmp/build -m releasedbg --yes
      - name: build
        run: xmake build --yes -vD stem && xmake build --yes -vD --group=tests
      - name: test
        run: xmake run --yes -vD --group=tests
      - name: Scheme tests
        run: xmake run --yes -vD --group=scheme_tests
