name: Test on Ubuntu 22.04 for Qt 6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build On Ubuntu
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
      - name: Install Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y cmake qt6-base-dev libqt6svg6-dev libfreetype6-dev libsqlite3-dev libjpeg-dev libcurl4-openssl-dev
      - name: Create Build Dir
        run: mkdir -p ${{github.workspace}}/build
      - name: Build using CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ${{github.workspace}} -DBUILD_TESTS=on -DTEXMACS_GUI=Qt6 && make -j8
      - name: Test
        run: cd ${{github.workspace}}/build && QT_QPA_PLATFORM=offscreen ctest -V


