name: Package for macOS

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  mac-package:
    name: Package On macOS
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          target: 'desktop'
          cache: 'true'
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.7.8
          actions-cache-folder: '.xmake-cache'
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            /Users/runner/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - name: xmake build and install
        run: |
            xmake config --yes
            xmake build --yes --verbose --diagnosis --jobs=8 --all
            xmake install -o build/macosx/x86_64/release/Mogan.app/Contents/Resources/ mogan_install
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          VERSION=${VERSION//\//}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Run Package Script
        working-directory: ${{github.workspace}}
        run: |
          packages/macos/package.sh
          mv ${{ github.workspace }}/build/Mogan.dmg ${{ github.workspace }}/Mogan_v${VERSION}.dmg
      - name: Upload Mogan.dmg
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: Mogan.dmg
          path: ${{ github.workspace }}/Mogan_*.dmg
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: ${{ github.workspace }}/Mogan_*.dmg
